import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { BasicTable } from '../components/BasicTable'
import 'bootstrap/dist/css/bootstrap.min.css';
import { SortingTable } from '../components/SortingTable';
import { FilteringTable } from '../components/FilteringTable';
import { PaginationTable } from '../components/PaginationTable';
import { RowSelection } from '../components/RowSelection';
import { ColumnOrder } from '../components/ColumnOrder';
import { ColumnHiding } from '../components/ColumnHiding';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
            <ColumnHiding />
        </div>
      </main>
    </div>
  )
}
